server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
      
      
spring:
  application:
    name: EVENTS-BOOKING
  config:
    import: configserver:http://localhost:8888
   
management:
  endpoints:
    web:
      exposure:
        include: '*'